added new Settings.jsx
putsan/teamchallenge_chat pull request #15
Opened 2023-11-15 13:16 UTC by Allochka11

Added new page - Settings, SettingsButton

2023-11-15 20:41 UTC, putsan requested changes
Загалом описав на що звернув увагу, не обов'язково на все відповідати.. можна тільки на те, де маєш що сказати або де є пряме питання))

Я б прийняв без змін, але все ж файл Settings треба перемістити та прибрати горизонтальну смугу прокрутки, яка чомусь з'явилася на твоїй сторінці. Досліди чому вона є, та позбудься)) бо теж колись такий баг часто мав і дуже його не любив)
![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/262e41d8-0720-4f7f-bba8-4ab223234bf9)

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/HeaderLobbyIcons/HeaderLobbyIcons.jsx
> -    <div className="Header">
це більше прохання до @Garpirik ..
Давай більше не писати назви класів з великої літери!!
А все з маленької і через дифіс, якщо кілька слів: .msgs-area

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/HeaderLobbyIcons/HeaderLobbyIcons.jsx
Молодець що підключила кнопку на сторінку, з якої можна перейти в налаштування))

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/Settings/Settings.jsx
> +            <Typography variant="body2" style={{ color: palette.grey[300] }}>
тут я все ж додав новий відтінок сірого в палітру, і вже виправив сам цей рядок..
цього кольору просто не було в переліку на окремій сторінці, де Ліза зібрала всі кольори які використала у дизайні..
якщо ще такі будуть, то краще додайте новий колір, а не беріть подібний.. @Garpirik @Allochka11

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/Settings/Settings.scss
Загалом мене цікавить який принцип для іменування класу ти використала?)
Можеш і в ПП відповісти..
Також чи тобі знайома методологій іменування по БЕМ ?? Хлопці ніби знайомі з нею..
https://en.bem.info/methodology/

Хоча на сайті надто гучно заявляють що методологію розробили у Яндекс, тож ще подумаю чи сам буду її використовувати надалі у проєктах))

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/Settings/SettingsButton.jsx
Прям так кнопку я не пригадую чи часто виносив у окремий компонент, досить цікаво.. можеш і далі так дробити)
бо я якщо б робив, то просто компонент заголовку би створив і там би вже був там текст (загол сторінки) та кнопки навігації. Бо цей загловок дуже схожий в обох сторінках, на твоїй налаштувань та на ст "[профіль іншого користувача](https://www.figma.com/file/1PQPdJ9OkJ25pwemCBkLPU/pet-project-team?type=design&node-id=391-1227&mode=dev)".. 

Тому думаю пізніше треба буде створити той заголовок компонентою..

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/Settings/SettingsButton.jsx
Загалом подумавши, думаю цю кнопку можна буде зробити універсальною і назвати приблизно IconButton
Яка прийматиме колбек (або ми наперед визначимо логіку), та назву стилю із констант.
І матиме 3 стилі, для пошуку, для переходу до налаштувань та меню "три крапочки".
![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/bf587761-4408-44fa-bbe1-3b854dbb3a78) ![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/0a45772a-d67c-4e15-b956-1088b67d3e22) ![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/b14f2e12-3984-4b3e-85d1-887e671418b9)

2023-11-15 20:41 UTC, putsan commented on frontend/src/components/Settings/Settings.jsx
Загалом, це окрема сторінка, тож її файл має бути у папці: frontend/src/pages
а не у компонентах..

2023-11-15 21:38 UTC, putsan commented
І ще забув одразу додати, ця сторінка [Settings](https://www.figma.com/file/1PQPdJ9OkJ25pwemCBkLPU/pet-project-team?type=design&node-id=420-1447&mode=dev) та "[Профіль інш користувача](https://www.figma.com/file/1PQPdJ9OkJ25pwemCBkLPU/pet-project-team?type=design&node-id=391-1227&mode=dev)" дуже схожі!!
**І можливо їх варто якось об'єднати?**
Створити спільну обгортку до прикладу. В якій будеуть розташовані компоненти з обох сторінок, і відображатися ті які потрібно, відповідно до флоу. так як до прикладу ми зробили зі сторінкою для frontend/src/pages/Authentication.jsx 

Що скажете? @Allochka11 @Garpirik @Mykokola 

<img src="https://github.com/putsan/teamchallenge_chat/assets/11944886/c56604bb-33ff-4a1f-aa68-1a8d6b4acadb" width="350"> <img src="https://github.com/putsan/teamchallenge_chat/assets/11944886/774004a0-861f-4774-9c36-517bf3753c25" width="350">

2023-11-18 16:25 UTC, putsan commented
Поки не буду закривати цей PR
Може згодом, а може вже як завершиш сторінку))

2023-11-23 19:03 UTC, Mykokola approved these changes

2023-11-23 19:20 UTC, Mykokola approved these changes

2023-11-23 19:20 UTC, Mykokola approved these changes, later dismissed

2023-11-28 12:05 UTC, putsan commented on frontend/src/pages/Settings/Settings.jsx
> +        </Grid>
Це я б виніс в окрему компоненту..
Бо тут трохи нагромаджено і багато пропсів((

  Або знову ж, щоб не виносити окремо.. то в SettingsItem можна зробити щоб передавати тільки 1 параметр, а все решту опрацьовувати "під капотом", в середині компоненти SettingsItem
```suggestion
        <Grid>
          <div className="separator" />
          <SettingsItem style={ICON_STYLES.LANGUAGE} />
          <div className="separator" style={{ marginLeft: "64px" }} />
          <SettingsItem style={ICON_STYLES.THEME}/>
          <div style={{ marginTop: "22px" }}>
            <SettingsItemstyle={ICON_STYLES.INFO} />
          </div>
        </Grid>
```
Приблизно так.. але тоді константу бажано перейменувати, або ж створити нову..
Продовжу цю ідею в інших коментаряхх

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/icons/IconFactory.jsx
Досить цікавий підхід який вітається))
хоча я б можливо намагався спрощено ці 3 іконки розмістити, без створення фабрити..
але на ці правки нема в нас часу, тому буде так..

Взагалі цю фабрику за необхідності можемо на інших сторінках для іконок використовувати?

2023-11-28 12:05 UTC, putsan commented on frontend/src/pages/Settings/Settings.jsx
> +  const themes = ["Світла", "Темна"];
Відповідно ці рядки можна буде перенести в SettingsItem

2023-11-28 12:05 UTC, putsan commented on frontend/src/app/constants.js
> +};
Загалом в константи можна заностит одразу той текст який будеш виводити користувачу, потім його легше знайти і віредагувати..

До прикладу 
```suggestion
export const SETTINGS_ITEM_STYLES = {
  THEME: "Тема",
  LANGUAGE: "Мова інтерфейсу",
  INFO: "Правила спільноти",
};
```
І цю константу всервіно можна використовувати далі в умовах...
Але й у неймінгу не може бути слово іконка, тому якщо для іконок треба теж костанту то розділиш

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
І ще треба зробити щоб клік (той що меню вибору відкриває) спрацьовував не тільки по тій маленькій іконці стрілокчки, а по майже всьому рядку SettingsItem
![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/48b6d064-d9ba-4dcb-a63c-344c85a06baf)

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
> +          {title}
І сам Title відповідно можна буде підставляти одразу з константи

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
> +        <IconFactory icon={icon} />
Для іконки тут все готово і дуже змінювати нічого не доведеться, можливо тільки констанки підправити

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
Відповідно:
```suggestion
const SettingsItem = ({ style }) => {
  const [isArrowRight, setIsArrowRight] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const languages = ["Українська", "English"];
  const themes = ["Світла", "Темна"];
  const isThemeStyle = style === SETTINGS_ITEM_STYLES.THEME;
  const isLangStyle = style === SETTINGS_ITEM_STYLES.LANGAUGE;
  const isInfoStyle = style === SETTINGS_ITEM_STYLES.INFO;

```

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
> +        {isModalOpen && <SettingsModal props={props} />}
І пропси як будуть в цьому файлі то просто передавати відповідні, в залежності від константи.. або нічого
```suggestion
        {isModalOpen && <SettingsModal props={isThemeStyle && themes || isLangStyle && langauges || null } />}
```
Приблизно так

2023-11-28 12:05 UTC, putsan commented on frontend/src/components/SettingsComponents/SettingsModal/SettingsModal.jsx
Конкретно SettingsModal не зовсім ок називати, бо це не зовсім модалка..
можна щось по-типу SettingsMenu or SettingsSubMenu or Select or SettingsSelect

2023-11-28 12:07 UTC, putsan approved these changes

2023-11-28 12:08 UTC, merged

2023-11-29 12:45 UTC, Allochka11 commented on frontend/src/components/icons/IconFactory.jsx
Так. Ідея в тому, щоб фабрика сама опрацьовувала іконки які нам треба, і виводила відповідні. Тому її можна використовувати з іконками інших сторінок.

2023-11-29 13:09 UTC, Allochka11 commented on frontend/src/components/SettingsComponents/SettingsItem.jsx
добре