Modal submit
putsan/teamchallenge_chat pull request #19
Opened 2023-11-27 23:29 UTC by Mykokola

2023-11-30 18:16 UTC, putsan commented
Би пасувало прикріпити скріншоти як ті модалики, чи ок виглядають)
У випадку коли вони не підключені ще ніде

2023-11-30 19:29 UTC, putsan requested changes
Загалом ніби сама логіка ок виглядає, але бардак залишив)
Поправ і злию..

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.jsx
> +          </svg>
Цю СВГшку би пасувало винести в окремий комопнент як мінімут, або вже сам компонент картинки користувача створити.. який потім відредагуємо коли будемо реальну картинку підтягувати..

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.scss
> +>>>>>>> Stashed changes
Все зайве прибрати
Бо й дужка здається зайва одна

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.scss
> +.modal {
і тут прибрати

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.jsx
> +>>>>>>> Stashed changes
те ж саме

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.jsx
> +        <button className="backgtoun-svg">
тут здається помилка в назві класу `className="backgtoun-svg` бо із CSS точно не поняти що це за елемент по такій назві, якщо тут не ясно

2023-11-30 19:29 UTC, putsan commented on frontend/src/components/modals/ModalType.jsx
> +      <h3 id="exit-accaunt"  className=" delete-gtoup">
ти можливо лінтери вимкнув? чи чому вони не виправило зайвий відступ??

в тебе перевірки взагалі запускаються при коміті? бо мали б..!

2023-11-30 19:30 UTC, putsan commented on frontend/src/components/modals/ModalsSubmit.jsx
> +          </svg>
І загалом чому файлом цю SVG не підключав? а сюди кодом вставив? 
Пригадай у чому різниця?

2023-12-01 03:56 UTC, putsan commented
Я вже злив PR #20 тож можеш підходящу модалку одразу підключити на кнопку "Видалити профіль"
![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/607cd621-6f5d-46a3-919d-98814acdfe0d)

2023-12-11 21:31 UTC, putsan requested changes
Модалку не показує по кліку, це по суті основне що треба виправити!!
Щоб вона з'являлася..

https://github.com/putsan/teamchallenge_chat/assets/11944886/596bf1a6-1816-4687-9d2d-87475cbf3662

2023-12-11 21:31 UTC, putsan commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +import { useState } from "react";
Цей імпорт має розташовуватися ближче до верху якщо не першим рядком..

2023-12-11 21:31 UTC, putsan commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +      ></ModalDelete>
```suggestion
      <ModalDelete
        type={`deleteChatWithUser`}
        show={modal}
        onClose={closeModal}
      />
```

2023-12-11 21:31 UTC, putsan commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +        type={`deleteChatWithUser`}
Назви типів `deleteChatWithUser` краще винести в константи у файл `frontend/src/app/constants.js`
І далі у всіх місцях де їх використовуєш підставляти із константи.. це дозволяє уникнути помилок, через опечатку в назві..

2023-12-15 22:12 UTC, Mykokola commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +        type={`deleteChatWithUser`}
+

2023-12-15 22:12 UTC, Mykokola commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +      ></ModalDelete>
+

2023-12-18 20:09 UTC, Mykokola commented on frontend/src/pages/UserInfo/UserInfo.jsx
> +import { useState } from "react";
+

2023-12-19 14:08 UTC, putsan approved these changes
Гарна робота!

Ще потрібні пізніше не критичні паравки, врахуй надалі будь ласка:
- по кліку на картинку в модалці нічого не повинно відбуватися!!
   А то зараз відкривається вікно вибору файлів, що є зайвим. Картинка буде підгружатися з БД відповідно до профілю чи чату, якого стосуватиметься модалка..
- всі варіанти шрифту, з оригінального дизайну, щоб надалі використовувалися в модалці, як до прикладу для username користувача чи назви групи..
![image](https://github.com/putsan/teamchallenge_chat/assets/11944886/e401054b-5d9e-482c-bc93-49a6a063f7a4)

2023-12-19 14:10 UTC, merged