Dev garpir modal
putsan/teamchallenge_chat pull request #7
Opened 2023-09-19 11:17 UTC by Garpirik

Added basic modal (need fix)

2023-09-24 20:27 UTC, putsan requested changes
Потрібно внести зміни в гілці, перш ніж її зливати
якщо будуть конфлікти, то пофіксити їх спочатку а тоді пушити

якщо хочеш ти можеш поправити, а можу й я це зробити..

2023-09-24 20:27 UTC, putsan commented on src/app/App.jsx
> +          <Route path="/ModalName" element={<ModalName/>} />
Саме окремий роут для модалки я не знаю щоб десь робили, тому це й називається модалка..
**Давай надалі узгоджувати коли треба створювати новий роут а коли ні!?**

Тим-паче він не використовуєтся, як виявилося.. в такому випадку такі зміни не варто пушити..

2023-09-24 20:27 UTC, putsan commented on src/index.css
Цікаво! я не використовував подібного раніше) розкажеш при нагоді більше про ці параметри..

2023-09-24 20:27 UTC, putsan commented on src/components/modal/modalName.jsx
загалом по коду модалки майже все ок, форматування не забувай робити і чому кнопка закоментована не розумію

але нюанс з кольорами і видимістю, навіть якщо зараз ми робимо суто скелет без стилів, варто робити щоб елементи були більш менш видимі а не чорне усе((

### є ж різниця:
<img src="https://github.com/putsan/teamchallenge_chat/assets/11944886/3a2131a2-723a-4e47-9a49-cbf12690d6ad" width="250" /> <img src="https://github.com/putsan/teamchallenge_chat/assets/11944886/a46485fb-6ea2-4087-851e-501c96531d74" width="250" />

2023-09-24 20:27 UTC, putsan commented on src/pages/StartFlow.jsx
> +        </Modal>
Так теж не має бути, навіть якщо ми використовуємо окремі готові компоненти з MUI, все ж коли передаємо так багато праметрів та контенту, то це краще виносити в окремий React component

2023-09-24 20:27 UTC, putsan commented on src/pages/Login.jsx
знову ж таки пушиш зайві компоненти й старий код, який сам прибрав в[ попередніх коммітах](https://github.com/putsan/teamchallenge_chat/commit/bbb0c174e2fc18e83719bf16e8b8024cf1626144), а це значить що не синхронізував останні зміни перед пушем своїх зімн..
цього фалу взагалі не має бути

2023-09-24 20:27 UTC, putsan commented on src/pages/Auth.jsx
файл зі старою назвою, відповідно це конфлікти

2023-09-24 20:27 UTC, putsan commented on src/app/App.jsx
ще й старий роут повторно пушиш

2023-09-29 20:07 UTC, Garpirik commented on src/app/App.jsx
> +          <Route path="/ModalName" element={<ModalName/>} />
Окей,про роут я просто забыл про него, я делал перерыв день-два из-за учебы

2023-09-29 22:03 UTC, merged